export interface SocialImageSpec {
  src: string;
  width: 1200;
  height: 630;
}

const image = (src: string): SocialImageSpec => ({
  src,
  width: 1200,
  height: 630,
});

/**
 * Stable, same-origin social preview assets generated by scripts/generate-og-images.mjs.
 * Locale variants intentionally share an image when they represent the same content.
 */
export const socialImages = {
  home: image("/og/home.jpg"),
  routes: image("/og/routes.jpg"),
  services: image("/og/services.jpg"),
  vipTransfer: image("/og/vip-transfer.jpg"),
  tours: {
    kapadokya: image("/og/tours/kapadokya.jpg"),
    pamukkale: image("/og/tours/pamukkale.jpg"),
    karadeniz: image("/og/tours/karadeniz.jpg"),
    ege: image("/og/tours/ege.jpg"),
  },
} as const;
